### ISSUE TITLE
passing a Path object as config_path can cause issues 

### ISSUE THREAD

**Issue by ArneBinder** [ChristophAlt/pytorch-ie-hydra-template#56]
in main entry scripts, i.e. `train.py`, `evaluate.py`, and `predict.py`. Should be `config_path=str(path / "configs")` instead.

**Comment by leonhardhennig** [comment]
to be precise, Hydra fails with "PosixPath' object has no attribute 'find'":

```bash
~/D/c/d/test-pytorch-ie3 (main) [2]> python src/train.py                         (test-pytorch-ie3) 
Traceback (most recent call last):
  File ".../miniconda3/envs/test-pytorch-ie3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File ".../miniconda3/envs/test-pytorch-ie3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 356, in <lambda>
    lambda: Hydra.create_main_hydra2(
  File ".../miniconda3/envs/test-pytorch-ie3/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 61, in create_main_hydra2
    config_loader: ConfigLoader = ConfigLoaderImpl(
  File ".../miniconda3/envs/test-pytorch-ie3/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 48, in __init__
    self.repository = ConfigRepository(config_search_path=config_search_path)
  File ".../miniconda3/envs/test-pytorch-ie3/lib/python3.9/site-packages/hydra/_internal/config_repository.py", line 66, in __init__
    self.initialize_sources(config_search_path)
  File ".../miniconda3/envs/test-pytorch-ie3/lib/python3.9/site-packages/hydra/_internal/config_repository.py", line 73, in initialize_sources
    scheme = self._get_scheme(search_path.path)
  File ".../miniconda3/envs/test-pytorch-ie3/lib/python3.9/site-packages/hydra/_internal/config_repository.py", line 144, in _get_scheme
    idx = path.find("://")
AttributeError: 'PosixPath' object has no attribute 'find'

```
